---
# Docker tasks for Decapod


- name: Install prerequisites
  become: true
  apt: name={{ item }} state=present
  with_items: "{{ docker_prerequisites }}"

- name: Install kernel extras
  become: true
  shell: apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual
  tags:
    - skip_ansible_lint

- name: Install docker key
  become: true
  apt_key: keyserver={{ docker_keyserver }} state=present id={{ docker_key }}

- name: Add docker repository
  become: true
  apt_repository: repo={{ docker_repo }} state=present

- name: Install docker-engine
  become: true
  apt: name=docker-engine={{ docker_version }} state=present update_cache=yes
  register: docker_engine_installed

- name: Pin docker-engine
  become: true
  command: apt-mark hold docker-engine
  when: docker_engine_installed.changed

- name: Add docker group
  become: true
  group: name=group state=present

- name: Add current user to the docker group
  become: true
  user: name={{ ansible_user }} groups=docker append=yes

- name: Ensure docker.service.d is created
  become: true
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: Ensure correct docker.conf for systemd is created
  become: true
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf

- name: Reload systemd units
  become: true
  command: systemctl daemon-reload
  tags:
    - skip_ansible_lint

- name: Restart docker
  become: true
  command: systemctl restart docker
  tags:
    - skip_ansible_lint

- name: Install docker-compose
  become: true
  pip: name=docker-compose
       version={{ docker_compose_version }}
       state=present
       executable=/usr/bin/pip
